# Build settings
baseurl: ""
markdown: kramdown
google_analytics: G-H0MBC5YE59
plugins:
  - jekyll-feed
  - jekyll-sitemap
sass:
  style: compressed # possible values: nested expanded compact compressed
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /articles/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages/g/"
    values:
      layout: "game"
      permalink: /:path/
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "assets"
    values:
      sitemap: false

# Schema Data
schema_type: Organization # Organization/Person

# Site Information
title: Edward Smith for Justice
description: Learn about Edward Smith, a Democratic candidate for Justice, 3rd Court of Appeals, Place 2.
# logo: /path/to/your/logo.png
# favicon: /path/to/your/favicon.png
url: https://smithforjustice.com

# Author Information
author:
  name: Edward Smith
  birth_place:
    locality: Dallas
    region: Texas
    country: USA
  description: I am native Texan who was born in Dallas, raised in Fort Worth and went to college at Texas A&M University in College Station. After law school my wife, Casey, and I headed west to California and settled in San Francisco. After a couple years we got an itch for adventure and left San Francisco for Santiago, Chile. In 2008 when our time in Santiago came to an end we moved to Austin and have called Austin home ever since.
  disambiguating_description: I am native Texan who was born in Dallas, raised in Fort Worth and went to college at Texas A&M University in College Station. After law school my wife, Casey, and I headed west to California and settled in San Francisco. After a couple years we got an itch for adventure and left San Francisco for Santiago, Chile. In 2008 when our time in Santiago came to an end we moved to Austin and have called Austin home ever since.
  address:
    locality: Austin
    region: Texas
    country: USA
  social_links:
    - https://www.facebook.com/Smith4Justice
    - https://www.twitter.com/SmithforJustice

# Social Profiles
twitter_username: SmithforJustice
facebook_username: Smith4Justice

# Contact Information
contact:
  # telephone: [+1.310.571.5210]
  email: contact@smithforjustice.com
